apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobi-deploy-01
  namespace: mobi-dev
  labels:
    app: mobility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobility
  template:
    metadata:
      labels:
        app: mobility
    spec:
      containers:
      - name: mobi-01
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs
          mountPath: "/log"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobi-deploy-02
  namespace: mobi-dev
  labels:
    app: mobility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobility
  template:
    metadata:
      labels:
        app: mobility
    spec:
      containers:
      - name: mobi-02
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs
          mountPath: "/log"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs